### ISSUE TITLE
not able to run project

### ISSUE THREAD

**Issue by sandor** [rjporter/polymer-2-fabric-edit#1]
Hey, I am just curious what you built here. 

I tried to install the project:

> downloaded your project from Git
> cd in terminal into your directory
> bower install polymer-2-edit

I am getting this error:

> bower                        ENOTFOUND Package polymer-2-edit not found

Could you please provide a little help on how I can run this project? 

Cheers & thanks!

**Comment by rjporter** [comment]
Cd info directory and type

bower install

don't include the name after install.

Let me know if you have other issues.

Ralph Porter

**Comment by sandor** [comment]
Thanks, I had also some problems with my bower installation, but now I got an install using "sudo bower install --allow-root"

Anyhow after using "polymer serve" I am getting a 404 on http://127.0.0.1:8081/bower_components/webcomponentsjs/webcomponents-light.js

Strangely the bower_components folder with the js script is existing in your project folder...

Sorry for all this ignorance, but I am really not an experienced developer :-)

**Comment by sandor** [comment]
Hi Ralph,

had some time to look at the project again – I had to fix a reference in the index.html:

`    <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
`
(slash before bower path)

But the main problem on my side was that I was only using Safari – that won't work. In chrome it is running fine now... Interesting project. What are you planning to do with it? Doy ou have a mail adress for talkin – I don't want to abuse this place for that...

**Comment by rjporter** [comment]
Thank you for your comments.  The / in the path to bower_components is not required if the bower_components directory is in the same directory as the rest of the project. 
Full or repetitive paths may be used.
